CreateConVar( "cfc_parachute_fall_speed", 200, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "Target fall speed while in a parachute.", 0, 50000 )
CreateConVar( "cfc_parachute_fall_lerp", 0.97, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "How quickly a parachute will reach its target fall speed.", 0, 10 )
CreateConVar( "cfc_parachute_horizontal_speed", 80, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "How quickly you move in a parachute.", 0, 50000 )
CreateConVar( "cfc_parachute_horizontal_speed_unstable", 40, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "How well you can control a parachute while holding another weapon.", 0, 50000 )
CreateConVar( "cfc_parachute_horizontal_speed_limit", 700, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "Max horizontal speed of a parachute.", 0, 50000 )
CreateConVar( "cfc_parachute_sprint_boost", 1.25, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "How much of a horizontal boost you get in a parachute while sprinting.", 1, 10 )
CreateConVar( "cfc_parachute_handling", 4, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "Improves parachute handling by making it easier to brake or chagne directions. 1 gives no handling boost, 0-1 reduces handling.", 0, 10 )

CreateConVar( "cfc_parachute_destabilize_min_gap", 0.3, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "Minimum time between direction changes while a parachute destabilizes, in seconds.", 0, 50000 )
CreateConVar( "cfc_parachute_destabilize_max_gap", 2, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "Maximum time between direction changes while a parachute destabilizes, in seconds.", 0, 50000 )
CreateConVar( "cfc_parachute_destabilize_max_direction_change", 30, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "Maximum angle change in a parachute's direction while it is destabilized.", 0, 180 )
CreateConVar( "cfc_parachute_destabilize_max_lurch", 125, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "Maximum downwards force a parachute can receive from random lurches while destabilized.", 0, 50000 )
CreateConVar( "cfc_parachute_destabilize_max_fall_lurch", 400, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "Maximum downwards velocity before a parachute stops being affected by lurch. Puts a soft-cap on how fast you plummet from shooting weapons.", 0, 50000 )
CreateConVar( "cfc_parachute_destabilize_lurch_chance", 0.2, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "The chance for an unstable parachute to lurch downwards when a direction change occurs.", 0, 1 )
CreateConVar( "cfc_parachute_destabilize_shoot_lurch_chance", 0.1, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "The chance for an unstable parachute to lurch downwards when the player shoots a bullet.", 0, 1 )
CreateConVar( "cfc_parachute_destabilize_shoot_change_chance", 0.25, { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "The chance for an unstable parachute's direction to change when the player shoots a bullet.", 0, 1 )

CreateConVar( "cfc_parachute_space_equip_speed", 370, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "The minimum falling speed required for a player to space-equip a parachute.", 0, 50000 )
CreateConVar( "cfc_parachute_space_equip_sv", 1, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "Press spacebar while falling to quickly equip a parachute. Defines the default value for players.", 0, 1 )
CreateConVar( "cfc_parachute_space_equip_double_sv", 0, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "Double tap spacebar to equip parachutes, instead of a single press. Defines the default value for players.", 0, 1 )
CreateConVar( "cfc_parachute_space_equip_weapon_sv", 1, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "Instantly switch back to your previous weapon when space-equipping a parachute. Defines the default value for players.", 0, 1 )

CreateConVar( "cfc_parachute_prev_weapon_on_close_sv", 1, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "Auto-selects the previous weapon upon closing the parachute. Defines the default value for players.", 0, 1 )
CreateConVar( "cfc_parachute_quick_close_sv", 1, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "Press walk and crouch to quickly close the parachute. Defines the default value for players.", 0, 1 )
